# Generated by Django 4.1.1 on 2022-10-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OwnerPanel', '0016_remove_listing_is_published_remove_listing_list_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
