# Generated by Django 4.1.1 on 2022-10-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_photo_2_listing_photo_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='House',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
