# Generated by Django 4.1.1 on 2022-10-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='House',
        ),
    ]
