# Generated by Django 4.1.1 on 2022-10-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_listing_bathrooms_remove_listing_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Hostel_Name',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
    ]
