# Generated by Django 4.1.1 on 2022-10-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_listing_hostel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Hostel_Name',
        ),
    ]
