# Generated by Django 4.1.1 on 2022-10-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_listing_realtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
    ]
