# Generated by Django 4.1.1 on 2022-10-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_alter_realtor_description_alter_realtor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(default='https://static.99acres.com/images/owner_pnava.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
